version: '3'
services:
  gitpulse-blue:
    image: your-image-name
    ports:
      - "4000"
    env_file:
      - .env
    restart: always
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:12201"
        tag: "gitpulse"

  gitpulse-green:
    image: your-image-name
    ports:
      - "4000"
    env_file:
      - .env
    restart: always
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:12201"
        tag: "gitpulse"