version: '3'
services:
  gitpulse-blue:
    build: .
    ports:
      - "4005:4000"
    env_file:
      - .env
    restart: always
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:12201"
        tag: "gitpulse"

  gitpulse-green:
    build: .
    ports:
      - "4006:4000"
    env_file:
      - .env
    restart: always
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:12201"
        tag: "gitpulse"

