version: '3.8'

services:
  gitdash-app:
    container_name: gitdash_app
    build:
      context: .
      args:
        - NODE_ENV=production
    env_file:
      - .env
    ports:
      - "5001:5001"
    restart: always